//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newBlogprj
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventBooking2
    {
        public int Event_ID { get; set; }
        public int mb_ID { get; set; }
        public System.DateTime BookingDate { get; set; }
        public int EmployeeJoinStatus { get; set; }
        public Nullable<int> BookingCount { get; set; }
        public Nullable<int> Event { get; set; }
    
        public virtual Event2 Event2 { get; set; }
    }
}
