//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newBlogprj
{
    using System;
    using System.Collections.Generic;
    
    public partial class forumLikebinding
    {
        public int ForumLike_ID { get; set; }
        public Nullable<int> fmb_ID { get; set; }
        public Nullable<int> ForumContentID { get; set; }
        public Nullable<int> Like_ID { get; set; }
    
        public virtual forumContent forumContent { get; set; }
        public virtual forumMemberBinding forumMemberBinding { get; set; }
        public virtual likeType likeType { get; set; }
    }
}
