//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newBlogprj
{
    using System;
    using System.Collections.Generic;
    
    public partial class forumMemberBinding
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public forumMemberBinding()
        {
            this.forumBinding = new HashSet<forumBinding>();
            this.forumLikebinding = new HashSet<forumLikebinding>();
            this.forumMessageBinding = new HashSet<forumMessageBinding>();
        }
    
        public int ForumMemberBinding_ID { get; set; }
        public Nullable<int> mb_ID { get; set; }
        public Nullable<int> ForumTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<forumBinding> forumBinding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<forumLikebinding> forumLikebinding { get; set; }
        public virtual forumType forumType { get; set; }
        public virtual memberdb memberdb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<forumMessageBinding> forumMessageBinding { get; set; }
    }
}
