//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newBlogprj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groupdb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Groupdb()
        {
            this.groupProductBinding = new HashSet<groupProductBinding>();
            this.MemberGroupOrder = new HashSet<MemberGroupOrder>();
        }
    
        public int Group_ID { get; set; }
        public string Group_startDate { get; set; }
        public string Group_endDate { get; set; }
        public Nullable<int> Group_targetNumber { get; set; }
        public Nullable<int> Group_type { get; set; }
        public string Group_description { get; set; }
        public Nullable<int> Member_ID { get; set; }
    
        public virtual GroupType GroupType { get; set; }
        public virtual memberdb memberdb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<groupProductBinding> groupProductBinding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberGroupOrder> MemberGroupOrder { get; set; }
    }
}
