//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace newBlogprj
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberGroupOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberGroupOrder()
        {
            this.groupOrderDetaildb = new HashSet<groupOrderDetaildb>();
        }
    
        public int MGOB_ID { get; set; }
        public Nullable<int> openmemberdb_ID { get; set; }
        public Nullable<int> Group_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
    
        public virtual Groupdb Groupdb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<groupOrderDetaildb> groupOrderDetaildb { get; set; }
        public virtual memberdb memberdb { get; set; }
    }
}
