//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace forumAPItest
{
    using System;
    using System.Collections.Generic;
    
    public partial class memberdb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public memberdb()
        {
            this.blogBinding = new HashSet<blogBinding>();
            this.Event = new HashSet<Event>();
            this.forumMemberBinding = new HashSet<forumMemberBinding>();
            this.memberGroupBinding = new HashSet<memberGroupBinding>();
            this.MemberGroupOrderBinding = new HashSet<MemberGroupOrderBinding>();
        }
    
        public int mb_ID { get; set; }
        public string mb_employeeName { get; set; }
        public string mb_employeeAccount { get; set; }
        public string mb_employeePassword { get; set; }
        public Nullable<int> mb_employeeDeptID { get; set; }
        public string mb_employeePhone { get; set; }
        public string mb_employeeEmail { get; set; }
        public string mb_employeeAddress { get; set; }
        public string mb_employeeGender { get; set; }
        public string mb_employeeHobby { get; set; }
        public string mb_employeePicture { get; set; }
        public string mb_employeeBirthday { get; set; }
        public string mb_employeeLiveCity { get; set; }
        public Nullable<System.DateTime> mb_employeeHireDate { get; set; }
        public string mb_employeeTransport { get; set; }
        public Nullable<int> mb_employeeState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blogBinding> blogBinding { get; set; }
        public virtual departmentdb departmentdb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<forumMemberBinding> forumMemberBinding { get; set; }
        public virtual MembersType MembersType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<memberGroupBinding> memberGroupBinding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberGroupOrderBinding> MemberGroupOrderBinding { get; set; }
    }
}
