//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace forumAPItest
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupOrderDetaildb
    {
        public int MGOB_ID { get; set; }
        public int GID { get; set; }
        public Nullable<int> GroupOrder_Quantity { get; set; }
        public string GroupOrder_Date { get; set; }
        public Nullable<bool> GroupOrder_State { get; set; }
        public string followmember_ID { get; set; }
    
        public virtual MemberGroupOrder MemberGroupOrder { get; set; }
    }
}
