//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace forumAPItest
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupProductBinding
    {
        public int GPB_ID { get; set; }
        public Nullable<int> Group_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Product_lowprice { get; set; }
    
        public virtual Groupdb Groupdb { get; set; }
        public virtual productdb productdb { get; set; }
    }
}
