//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace forumAPItest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class final_pEntities : DbContext
    {
        public final_pEntities()
            : base("name=final_pEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Group_Order_Binding> Group_Order_Binding { get; set; }
        public virtual DbSet<Group_Product_Binding> Group_Product_Binding { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<pGroupdb> pGroupdb { get; set; }
        public virtual DbSet<pProductdb> pProductdb { get; set; }
    }
}
